packages:
  - monaco-editor
  - image-viewer
  - file-viewer
  - csv-viewer
  - pdf-viewer
  - font-viewer
  - sqlite-editor
  - zip-provider
  - iso-provider
  - dsstore-viewer

onlyBuiltDependencies:
  - esbuild
